version: "3.6"

services:

  flask:
    build:
      dockerfile: Dockerfile.flask
      context: ./flask
    depends_on:
      - mariadb
    working_dir: /app
    volumes:
      - ./flask:/app
    container_name: flask
    ports:
      - 3031:3031
    restart: always

  mariadb:
    build:
      dockerfile: Dockerfile.mariadb
      context: ./mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=root
      - TZ=UTC
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    build:
      dockerfile: Dockerfile.nginx
      context: ./nginx
    container_name: nginx
    depends_on:
      - flask
    ports:
      - 443:443
    volumes: 
     - ./nginx/certs:/etc/nginx/certs
    restart: always

volumes:
  data:
    
