FROM python:3.9-slim-buster

RUN apt-get update \
    && apt-get -yy install libmariadb-dev \
    && apt-get -y install gcc

EXPOSE 3031
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
COPY wsgi.ini /etc/uwsgi/
CMD ["uwsgi", "--uid", "33", "wsgi.ini"]

